version: '3.4'

services:
  
  eventsourcingcqrs.api:
    container_name: api
    image: ${DOCKER_REGISTRY-}eventsourcingcqrsapi
    build:
      context: ../
      dockerfile: src/EventSourcingCqrs.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1legradev@
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on: 
      - eventstore.db
      - postgres.db
    
  eventstore.db:
    container_name: eventstore
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
  
  postgres.db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: X@bLVUv7bKH=xy
    ports:
      - "5435:5432"
